language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "pypy"
before_install:
  - sudo apt-get install libudev-dev gccxml
  - sudo apt-get install libglib2.0-dev
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
after_install:
  - python build_bindings.py --binding pygobject --force-build
script: py.test --junitxml=tests.xml --enable-privileged -rfEsxX
